import { Movie } from './types';

export const MOVIES: Movie[] = [
  // --- BANGLA MOVIES ---
  {
    id: 'hawa-2022',
    title: 'Hawa',
    titleBn: 'হাওয়া',
    originalTitle: 'Hawa',
    language: 'bangla',
    year: 2022,
    rating: 8.2,
    duration: '2h 17m',
    genres: ['Mystery', 'Thriller', 'Drama'],
    genresBn: ['রহস্য', 'থ্রিলার', 'ড্রামা'],
    director: 'Mejbaur Rahman Sumon',
    directorBn: 'মেজবাউর রহমান সুমন',
    cast: ['Chanchal Chowdhury', 'Nazifa Tushi', 'Shariful Raj', 'Sumon Anowar'],
    bannerUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=400&auto=format&fit=crop',
    description: 'A team of professional fishermen finds a mysterious beautiful young woman in their catching net in the deep middle sea.',
    descriptionBn: 'গভীর সমুদ্রে মাছ ধরার জালে আটকা পড়ে এক রহস্যময় রূপবতী তরুণী। তাকে কেন্দ্র করে ট্রলারের জেলেদের মনে দানা বাঁধে নানা সংশয় ও আদিম উত্তেজনা।',
    features: ['Full HD 1080p', 'Dolby Digital 5.1', 'Bangla Audio'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-crashing-waves-in-the-ocean-from-above-41858-large.mp4',
  },
  {
    id: 'aynabaji-2016',
    title: 'Aynabaji',
    titleBn: 'আয়নাবাজি',
    originalTitle: 'Aynabaji',
    language: 'bangla',
    year: 2016,
    rating: 8.9,
    duration: '2h 24m',
    genres: ['Crime', 'Thriller', 'Mystery'],
    genresBn: ['অপরাধ', 'থ্রিলার', 'রহস্য'],
    director: 'Amitabh Reza Chowdhury',
    directorBn: 'অমিতাভ রেজা চৌধুরী',
    cast: ['Chanchal Chowdhury', 'Masuma Rahman Nabila', 'Partha Barua', 'Lutfur Rahman George'],
    bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=400&auto=format&fit=crop',
    description: 'Ayna is a human chameleon. He can transform into anyone he wants. A crime thriller that delves deep into the dark side of a bustling metropolis.',
    descriptionBn: 'আয়না একজন অসাধারণ অভিনেতা, যে জীবিকার তাগিদে অন্যের হয়ে জেল খাটে। কিন্তু এই অদ্ভুত পেশাই একদিন তার জীবনের জন্য হুমকি হয়ে দাঁড়ায়।',
    features: ['4K Ultra HD', 'Dolby Atmos', 'Bangla Audio'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-car-headlights-under-manhole-steam-at-night-42171-large.mp4',
  },
  {
    id: 'monpura-2009',
    title: 'Monpura',
    titleBn: 'মনপুরা',
    originalTitle: 'Monpura',
    language: 'bangla',
    year: 2009,
    rating: 8.5,
    duration: '2h 20m',
    genres: ['Romance', 'Drama', 'Musical'],
    genresBn: ['রোমান্স', 'ড্রামা', 'মিউজিক্যাল'],
    director: 'Giasuddin Selim',
    directorBn: 'গিয়াসউদ্দিন সেলিম',
    cast: ['Chanchal Chowdhury', 'Farhana Mili', 'Fazlur Rahman Babu', 'Mamunur Rashid'],
    bannerUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=400&auto=format&fit=crop',
    description: 'A tragic romantic movie set in a beautiful isolated island named Monpura, following a love story against ancestral rivalry.',
    descriptionBn: 'মনপুরা নামক এক বিচ্ছিন্ন দ্বীপে নির্বাসিত যুবক সোনাই এবং খেয়াঘাটের মাঝির মেয়ে পরীর মধ্যকার এক অমর ও বেদনাবিধুর প্রেমকাহিনী।',
    features: ['HQ Audio', 'Widescreen 16:9', 'Classic Soundtrack'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-thick-green-forests-around-a-river-42808-large.mp4',
  },
  {
    id: 'debi-2018',
    title: 'Debi',
    titleBn: 'দেবী',
    originalTitle: 'Debi: Misir Ali Prothombar',
    language: 'bangla',
    year: 2018,
    rating: 7.4,
    duration: '1h 45m',
    genres: ['Horror', 'Mystery', 'Psychological'],
    genresBn: ['হরর', 'রহস্য', 'মনস্তাত্ত্বিক'],
    director: 'Anam Biswas',
    directorBn: 'অনম বিশ্বাস',
    cast: ['Jaya Ahsan', 'Chanchal Chowdhury', 'Animesh Aich', 'Sabnam Faria'],
    bannerUrl: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?q=80&w=400&auto=format&fit=crop',
    description: 'Based on Humayun Ahmed\'s famous novel, Misir Ali investigates a mysterious psychological block involving a woman who can predict events.',
    descriptionBn: 'হুমায়ূন আহমেদের বিখ্যাত উপন্যাস অবলম্বনে নির্মিত। অতিপ্রাকৃতিক ক্ষমতাসম্পন্ন তরুণী রানুর মানসিক রহস্য উন্মোচনে নামেন যুক্তিবাদী মিসির আলি।',
    features: ['Full HD 1080p', 'English Subtitles', 'Dual Stereo'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-walking-along-a-dark-street-under-the-rain-41712-large.mp4',
  },
  {
    id: 'shurongo-2023',
    title: 'Shurongo',
    titleBn: 'সুরঙ্গ',
    originalTitle: 'Shurongo',
    language: 'bangla',
    year: 2023,
    rating: 7.8,
    duration: '2h 30m',
    genres: ['Crime', 'Drama', 'Thriller'],
    genresBn: ['অপরাধ', 'ড্রামা', 'থ্রিলার'],
    director: 'Raihan Rafi',
    directorBn: 'রায়হান রাফী',
    cast: ['Afran Nisho', 'Tama Mirza', 'Mostafa Monwar'],
    bannerUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=400&auto=format&fit=crop',
    description: 'A desperate husband makes plans of a spectacular bank heist by digging an underground tunnel to win back his materialistic wife.',
    descriptionBn: 'বিত্তলোভী স্ত্রীকে সুখী করার অন্ধ মোহে এক অতি সাধারণ স্বামী ব্যাংক ডাকাতির এক দুঃসাহসিক ও শ্বাসরুদ্ধকর সুড়ঙ্গ পরিকল্পনা তৈরি করে।',
    features: ['4K Dolby Vision', 'Atmos Audio', 'Multiple Tracks'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-sparklers-burning-in-the-dark-43301-large.mp4',
  },
  {
    id: 'shrabon-megher-din-1999',
    title: 'Shrabon Megher Din',
    titleBn: 'শ্রাবণ মেঘের দিন',
    originalTitle: 'Shrabon Megher Din',
    language: 'bangla',
    year: 1999,
    rating: 8.4,
    duration: '2h 15m',
    genres: ['Drama', 'Musical', 'Romance'],
    genresBn: ['ড্রামা', 'মিউজিক্যাল', 'রোমান্স'],
    director: 'Humayun Ahmed',
    directorBn: 'হুমায়ূন আহমেদ',
    cast: ['Zahid Hasan', 'Meher Afroz Shaon', 'Mahfuz Ahmed', 'Mukti'],
    bannerUrl: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?q=80&w=400&auto=format&fit=crop',
    description: 'A beautiful masterpiece focusing on monsoon, folk songs, love triangle, and rural life in a scenic Bangladeshi village.',
    descriptionBn: 'বর্ষার আবহ, লোকসংগীত, গ্রামীণ জীবনধারা ও এক করুণ ত্রিকোণ প্রেমের টানাপোড়েন নিয়ে মেসবাহুল হক ও কুসুমের অনন্য কাহিনী।',
    features: ['Remastered Video', 'Hi-Fi Folk Track', 'Aesthetic Visuals'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-raindrops-on-green-leaves-close-up-42861-large.mp4',
  },

  // --- ENGLISH MOVIES ---
  {
    id: 'interstellar-2014',
    title: 'Interstellar',
    titleBn: 'ইন্টারস্টেলার',
    originalTitle: 'Interstellar',
    language: 'english',
    year: 2014,
    rating: 8.7,
    duration: '2h 49m',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    genresBn: ['বিজ্ঞান-কল্পকাহিনী', 'অ্যাডভেঞ্চার', 'ড্রামা'],
    director: 'Christopher Nolan',
    directorBn: 'ক্রিস্টোফার নোলান',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    bannerUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=400&auto=format&fit=crop',
    description: 'When Earth becomes uninhabitable, a team of explorers travels through a wormhole in space in an attempt to ensure humanity\'s survival.',
    descriptionBn: 'পৃথিবীর মেয়াদ ফুরিয়ে আসার পর, মানবজাতির অস্তিত্ব রক্ষার লক্ষ্যে মহাকাশে ওয়ার্মহোল দিয়ে এক দুঃসাহসিক অভিযানে পাড়ি জমান একদল নভোচারী।',
    features: ['4K UHD + IMAX', 'Dolby Atmos 7.1', 'English & Bangla Dub'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-rotating-and-glowing-high-tech-planet-earth-31952-large.mp4',
  },
  {
    id: 'inception-2010',
    title: 'Inception',
    titleBn: 'ইনসেপশন',
    originalTitle: 'Inception',
    language: 'english',
    year: 2010,
    rating: 8.8,
    duration: '2h 28m',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    genresBn: ['বিজ্ঞান-কল্পকাহিনী', 'অ্যাকশন', 'থ্রিলার'],
    director: 'Christopher Nolan',
    directorBn: 'ক্রিস্টোফার নোলান',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    bannerUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=400&auto=format&fit=crop',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    descriptionBn: 'মানুষের অবচেতন মগ্ন মন থেকে স্বপ্ন চুরির প্রযুক্তি ব্যবহার করে বড় বড় করপোরেট তথ্য পাচারকারী এক চোরকে দেওয়া হয় মনের গভীরে নতুন বুদ্ধি বোনার জটিল দায়িত্ব।',
    features: ['4K HDR', 'Dolby Audio', 'Multi-Subs'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-panning-down-on-glowing-lights-in-the-night-city-31968-large.mp4',
  },
  {
    id: 'the-dark-knight-2008',
    title: 'The Dark Knight',
    titleBn: 'দ্য ডার্ক নাইট',
    originalTitle: 'The Dark Knight',
    language: 'english',
    year: 2008,
    rating: 9.0,
    duration: '2h 32m',
    genres: ['Action', 'Crime', 'Drama'],
    genresBn: ['অ্যাকশন', 'অপরাধ', 'ড্রামা'],
    director: 'Christopher Nolan',
    directorBn: 'ক্রিস্টোফার নোলান',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Maggie Gyllenhaal'],
    bannerUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400&auto=format&fit=crop',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests.',
    descriptionBn: 'গথাম শহরে জোকার নামক এক কুখ্যাত অপরাধীর তাণ্ডব ঠেকাতে ব্যাটম্যানকে সম্মুখীন হতে হয় তার জীবনের পরম মনস্তাত্ত্বিক ও শারীরিক পরীক্ষার।',
    features: ['Ultra HD', 'DTS-HD Master Audio', 'Director\'s Edition'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-movement-of-a-car-dashboard-lights-in-a-traffic-jam-41711-large.mp4',
  },
  {
    id: 'oppenheimer-2023',
    title: 'Oppenheimer',
    titleBn: 'ওপেনহাইমার',
    originalTitle: 'Oppenheimer',
    language: 'english',
    year: 2023,
    rating: 8.4,
    duration: '3h 0m',
    genres: ['Biography', 'Drama', 'History'],
    genresBn: ['জীবনী', 'ড্রামা', 'ইতিহাস'],
    director: 'Christopher Nolan',
    directorBn: 'ক্রিস্টোফার নোলান',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    bannerUrl: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?q=80&w=400&auto=format&fit=crop',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
    descriptionBn: 'আমেরিকান পদার্থবিজ্ঞানী জে. রবার্ট ওপেনহাইমারের জীবন ও ২য় বিশ্বযুদ্ধের সময় পারমাণবিক বোমা তৈরিতে ম্যানহাটন প্রজেক্টে তার অনন্য অবদানের কাহিনী।',
    features: ['4K Ultra HD', 'TrueHD Dolby Atmos', 'Director\'s Audio Comment'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-magical-bright-particles-floating-gently-in-the-air-43187-large.mp4',
  },
  {
    id: 'dune-2-2024',
    title: 'Dune: Part Two',
    titleBn: 'ডিউন: পার্ট টু',
    originalTitle: 'Dune: Part Two',
    language: 'english',
    year: 2024,
    rating: 8.6,
    duration: '2h 46m',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    genresBn: ['বিজ্ঞান-কল্পকাহিনী', 'অ্যাডভেঞ্চার', 'অ্যাকশন'],
    director: 'Denis Villeneuve',
    directorBn: 'দুনি ভিলনোভ',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Austin Butler'],
    bannerUrl: 'https://images.unsplash.com/photo-1547234935-80c7145ec969?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1547234935-80c7145ec969?q=80&w=400&auto=format&fit=crop',
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    descriptionBn: 'পরিবার ধ্বংসকারীদের বিরুদ্ধে প্রতিশোধ নিতে পল অ্যাট্রিডিস চানি ও ফ্রেমেন উপজাতির সাথে এক হয়ে মরুভূমির মহাকাব্যিক লড়াইয়ে অবতীর্ণ হন।',
    features: ['4K Dolby Vision', 'Auro 3D', 'Dual English/Bangla Subs'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-mysterious-scifi-glowing-lines-on-golden-dunes-31518-large.mp4',
  },
  {
    id: 'titanic-1997',
    title: 'Titanic',
    titleBn: 'টাইটানিক',
    originalTitle: 'Titanic',
    language: 'english',
    year: 1997,
    rating: 7.9,
    duration: '3h 14m',
    genres: ['Romance', 'Drama'],
    genresBn: ['রোমান্স', 'ড্রামা'],
    director: 'James Cameron',
    directorBn: 'জেমস ক্যামেরন',
    cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane', 'Kathy Bates'],
    bannerUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=400&auto=format&fit=crop',
    description: 'A seventeen-year-old aristocrat falls in love with a kind-hearted but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
    descriptionBn: 'অভিজাত বংশের রূপবতী কিশোরী রোজ বিলাসবহুল টাইটানিক জাহাজে এক ছন্নছাড়া দরদী চিত্রশিল্পী জ্যাকের বাঁধনহারা মায়ায় জড়িয়ে পড়ে।',
    features: ['Remastered 4K HDR', 'Dolby Digital 5.1', 'English Hi-Fi'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-calm-blue-running-sea-waves-41865-large.mp4',
  },

  // --- INDIAN MOVIES ---
  {
    id: 'three-idiots-2009',
    title: '3 Idiots',
    titleBn: '৩ ইডিয়টস',
    originalTitle: '3 Idiots',
    language: 'indian',
    year: 2009,
    rating: 8.4,
    duration: '2h 50m',
    genres: ['Comedy', 'Drama'],
    genresBn: ['কমেডি', 'ড্রামা'],
    director: 'Rajkumar Hirani',
    directorBn: 'রাজকুমার হিরানি',
    cast: ['Aamir Khan', 'Madhavan', 'Sharman Joshi', 'Kareena Kapoor'],
    bannerUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=400&auto=format&fit=crop',
    description: 'Two friends search for their long-lost companion Rancho, recalling their college life and the impact Rancho had on their ways of thinking.',
    descriptionBn: 'দুই বন্ধু তাদের বহুদিনের নিখোঁজ সহপাঠী র‌্যাঞ্চোকে খুঁজতে বের হয় এবং তাদের ইঞ্জিনিয়ারিং শিক্ষা ব্যবস্থার সাথে লড়াইয়ের স্মৃতি রোমন্থন করে।',
    features: ['1080p Digital Direct', 'Bollywood Classic', 'Dual Audio'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-group-of-students-studying-in-a-library-close-up-42777-large.mp4',
  },
  {
    id: 'rrr-2022',
    title: 'RRR',
    titleBn: 'আরআরআর',
    originalTitle: 'Roudram Ranam Rudhiram',
    language: 'indian',
    year: 2022,
    rating: 7.8,
    duration: '3h 7m',
    genres: ['Action', 'Drama', 'Adventure'],
    genresBn: ['অ্যাকশন', 'ড্রামা', 'অ্যাডভেঞ্চার'],
    director: 'S.S. Rajamouli',
    directorBn: 'এস.এস. রাজামৌলি',
    cast: ['N.T. Rama Rao Jr.', 'Ram Charan', 'Ajay Devgn', 'Alia Bhatt'],
    bannerUrl: 'https://images.unsplash.com/photo-1599733589046-9b8308b5b50d?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1599733589046-9b8308b5b50d?q=80&w=400&auto=format&fit=crop',
    description: 'A fictional story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.',
    descriptionBn: '১৯২০-এর দশকে ভারতীয় দুই কিংবদন্তি বিপথগামী বিপ্লবীর মধ্যে গড়ে ওঠা এক অবিচ্ছেদ্য বন্ধুত্ব এবং ঔপনিবেশিক শক্তির বিরুদ্ধে তাদের মহাকাব্যিক সংগ্রাম।',
    features: ['4K Dolby Vision', 'Atmos Audio', 'Multi-Language Dubs'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-fiery-embers-and-smoke-floating-in-the-dark-43302-large.mp4',
  },
  {
    id: 'baahubali-2-2017',
    title: 'Baahubali 2: The Conclusion',
    titleBn: 'বাহুবলী ২: দ্য কনক্লুশন',
    originalTitle: 'Baahubali: The Conclusion',
    language: 'indian',
    year: 2017,
    rating: 8.2,
    duration: '2h 47m',
    genres: ['Action', 'Fantasy', 'Drama'],
    genresBn: ['অ্যাকশন', 'ফ্যান্টাসি', 'ড্রামা'],
    director: 'S.S. Rajamouli',
    directorBn: 'এস.এস. রাজামৌলি',
    cast: ['Prabhas', 'Rana Daggubati', 'Anushka Shetty', 'Tamannaah Bhatia'],
    bannerUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=400&auto=format&fit=crop',
    description: 'When Mahendra Baahubali learns about the tragic assassination of his father, he raises an army to defeat the tyrant Bhallaladeva.',
    descriptionBn: 'মহেন্দ্র বাহুবলী যখন তার পিতা অমরেন্দ্র বাহুবলীর করুণ বিশ্বাসঘাতকতার হত্যার কথা জানতে পারে, তখন সে মহিষ্মতী রাজ্য উদ্ধারে সৈন্য দল গড়ে তোলে।',
    features: ['Full HD 1080p', 'Dual Bangla/Hindi', 'Surround Sound'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-a-burning-flame-in-slow-motion-41804-large.mp4',
  },
  {
    id: 'dangal-2016',
    title: 'Dangal',
    titleBn: 'দাঙ্গাল',
    originalTitle: 'Dangal',
    language: 'indian',
    year: 2016,
    rating: 8.3,
    duration: '2h 41m',
    genres: ['Biography', 'Drama', 'Sport'],
    genresBn: ['জীবনী', 'ড্রামা', 'খেলাধুলা'],
    director: 'Nitesh Tiwari',
    directorBn: 'নিতেশ তিওয়ারি',
    cast: ['Aamir Khan', 'Sakshi Tanwar', 'Fatima Sana Shaikh', 'Sanya Malhotra'],
    bannerUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=400&auto=format&fit=crop',
    description: 'Mahavir Singh Phogat, a former wrestler, decides to fulfill his dream of winning a gold medal for his country by training his daughters in wrestling.',
    descriptionBn: 'সাবেক কুস্তিগীর মহাবীর সিং ফোগাট সমাজের সকল প্রতিবন্ধকতা উপেক্ষা করে তার নিজের দুই মেয়ে গীতা ও ববিতাকে বিশ্বমানের কুস্তিগীর হিসেবে গড়ে তোলেন।',
    features: ['Full HD 1080p', 'HQ Acoustic Stereo', 'Subtitles Loaded'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-ropes-and-athletic-equipment-in-a-crossfit-gym-42618-large.mp4',
  },
  {
    id: 'jawan-2023',
    title: 'Jawan',
    titleBn: 'জাওয়ান',
    originalTitle: 'Jawan',
    language: 'indian',
    year: 2023,
    rating: 7.0,
    duration: '2h 49m',
    genres: ['Action', 'Thriller', 'Crime'],
    genresBn: ['অ্যাকশন', 'থ্রিলার', 'অপরাধ'],
    director: 'Atlee Kumar',
    directorBn: 'অ্যাটলি কুমার',
    cast: ['Shah Rukh Khan', 'Nayanthara', 'Vijay Sethupathi', 'Deepika Padukone'],
    bannerUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=400&auto=format&fit=crop',
    description: 'A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.',
    descriptionBn: 'সমাজ ও রাষ্ট্র ব্যবস্থার অবিচার রুখে দিতে এক সাবেক সেনাপ্রধানের গড়ে তোলা এক রোমাঞ্চকর অসম লড়াই ও পারিবারিক প্রতিশোধের গল্প।',
    features: ['4K UHD HDR', 'Dolby Digital Voice', 'Dual Hindi/Bangla Dub'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-shaking-colored-dust-particles-against-neon-lights-31959-large.mp4',
  },
  {
    id: 'sholay-1975',
    title: 'Sholay',
    titleBn: 'শোলে',
    originalTitle: 'Sholay',
    language: 'indian',
    year: 1975,
    rating: 8.1,
    duration: '3h 24m',
    genres: ['Action', 'Adventure', 'Comedy'],
    genresBn: ['অ্যাকশন', 'অ্যাডভেঞ্চার', 'কমেডি'],
    director: 'Ramesh Sippy',
    directorBn: 'রমেশ সিপ্পি',
    cast: ['Dharmendra', 'Sanjeev Kumar', 'Hema Malini', 'Amitabh Bachchan', 'Jaya Bachchan', 'Amjad Khan'],
    bannerUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=400&auto=format&fit=crop',
    description: 'After his family is murdered by a notorious dacoit Gabbar Singh, a retired police officer enlists two outlaws to capture him.',
    descriptionBn: 'কুখ্যাত ডাকাত গব্বর সিংয়ের হিংস্র প্রতিহিংসার শিকার হয়ে এক অবসরপ্রাপ্ত পুলিশ অফিসার দুই সাহসী ভবঘুরেকে ভাড়া করেন তাকে বন্দী করতে।',
    features: ['70mm Original Remastered', 'Golden Era Classic', 'Stereo 2.0 Track'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-riding-horses-on-a-dry-dusty-country-path-50143-large.mp4',
  }
];

export const GENRES_EN = ['All', 'Action', 'Thriller', 'Drama', 'Mystery', 'Sci-Fi', 'Romance', 'Crime', 'Biography', 'Adventure'];
export const GENRES_BN = ['সবগুলো', 'অ্যাকশন', 'থ্রিলার', 'ড্রামা', 'রহস্য', 'বিজ্ঞান-কল্পকাহিনী', 'রোমান্স', 'অপরাধ', 'জীবনী', 'অ্যাডভেঞ্চার'];
